version: '2'
services:
  nanopub:
    image: tkuhn/nanopub-server
    restart: unless-stopped
    depends_on:
      - db
      - rdfsink
    environment:
      - NPS_MONGODB_HOST=db
      - NPS_COLLECT_NANOPUBS_ENABLED=true
#      - NPS_PUBLIC_URL=http://.../
      - NPS_POST_NEW_NANOPUBS_TO=http://rdfsink:80
      - NPS_WAIT_MS_BEFORE_PEER_SCAN=1000
    ports:
      - 8080:8080
  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data/mongodb:/data/db
  rdfsink:
    image: tkuhn/rdfsink
    restart: unless-stopped
    depends_on:
      - virtuoso
    environment:
      - ENDPOINT=http://virtuoso:8890/sparql
      - UPDATE_ENDPOINT=http://virtuoso:8890/sparql
      - MODULE=nanopub
    volumes:
      - ./data/rdfsink:/data
  virtuoso:
    image: tenforce/virtuoso
    restart: unless-stopped
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - SPARQL_UPDATE=true
    volumes:
      - ./data/virtuoso:/data
  grlc:
    image: clariah/grlc:dev
    restart: unless-stopped
    ports:
     - 8001:80
    environment:
     - DEBUG=true
     - USERMAP_GID=1000
     - USERMAP_UID=1000
    volumes:
     - ./data/grlc/nanopub-api:/home/grlc/queries
